require('code/controllers/_appCtrl.js');
require('code/controllers/loginCtrl.js');
require('code/controllers/profileCtrl.js');
require('code/controllers/roomCtrl.js');
require('code/controllers/sideCtrl.js');
require('code/controllers/signupCtrl.js');
require('code/services/_appSvc.js');
require('code/services/authSvc.js');
require('code/app');